### ISSUE TITLE
Warnings in Chrome console

### ISSUE THREAD

**Issue by Chi-teck** [ghosh/Micromodal#327]
The following message appears in Chrome console when micro modal is open.

> micro-modal.min.js [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by iKevinShah** [comment]
Hi, 

Any update on this?

Just adding `{passive: false}` to all `addEventListener` in source seems to solve the problem but not sure about the ramifications. Didn't get time to check.

Is this being looked into @Devs? Or is it okay to place `{passive: false}` ?

**Comment by ghosh** [comment]
Should be fixed with #478

**Comment by romainpoirier** [comment]
I'm still getting the error with the latest version served by `https://cdn.jsdelivr.net/npm/micromodal/dist/micromodal.min.js`.
Why? It seems to have been fixed, then reverted back.
